baseURL = "https://khanhkid.github.io/"
languageCode = "en-us"
title = "Nơi tui viết chuyện đời "
theme = "ezhil-customize"
publishDir = "../../"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
#googleAnalytics = "UA-123-45"
# Your Disqus sortname.
disqusShortname = "khanhkid"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Sooner better than later"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true

# Main menu which appears below site header.
[[menu.main]]
name = "Trang chủ"
url = "/"
weight = 1

[[menu.main]]
name = "Về Tui"
url = "/about"
weight = 2

[[menu.main]]
name = "Chủ đề"
url = "/tags"
weight = 3

[[menu.main]]
name = "Phim"
url = "/tags/movies"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/khanhkid"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/khanhkid/"

# Enable tags.
[taxonomies]
   tag = "tags"